# Generated by Django 4.2 on 2024-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projet_options_remove_projet_unique_nom_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='est_accepte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('accepté', 'Accepté'), ('rejeté', 'Rejeté')], default='en attente', max_length=50),
        ),
    ]
