# Generated by Django 4.2 on 2024-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rapport_est_accepte_alter_rapport_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='est_accepte',
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=models.CharField(default='en attente', max_length=50),
        ),
    ]
