# Generated by Django 4.2 on 2024-10-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RapportApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_archive', models.URLField()),
                ('date_archive', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapportApp.rapport')),
            ],
        ),
    ]
